In [1]:
import folium

In [2]:
import pandas as pd

In [5]:
df1=pd.read_csv('./data-hut-starbucks-location-dataset/starbucks_2018_11_06.csv')
df1

,name,url,street_address,city,state,zip_code,country,phone_number_1,phone_number_2,fax_1,...,email_2,website,open_hours,latitude,longitude,facebook,twitter,instagram,pinterest,youtube
0,交易廣場,https://www.starbucks.com/store-locator/store/6,中環交易廣場3樓平台,香港,CN,NaN,US,21473739,NaN,NaN,...,NaN,NaN,"Wednesday : 6:30 AM to 8:30 PM, Thursday : 6:3...",22.283940,114.158190,NaN,NaN,NaN,NaN,NaN
1,德福廣場,https://www.starbucks.com/store-locator/store/8,九龍灣德福廣場一期A大堂G1A號,香港,CN,0,US,27541323,NaN,NaN,...,NaN,NaN,"Wednesday : 7:00 AM to 10:30 PM, Thursday : 7:...",22.322870,114.213440,NaN,NaN,NaN,NaN,NaN
2,荷李活廣場,https://www.starbucks.com/store-locator/store/1,九龍鑽石山荷里活廣場2樓298號鋪,香港,CN,NaN,US,29554570,NaN,NaN,...,NaN,NaN,"Wednesday : 8:30 AM to 10:30 PM, Thursday : 8:...",22.340700,114.201690,NaN,NaN,NaN,NaN,NaN
3,機鐵香港站,https://www.starbucks.com/store-locator/store/13,機鐵香港站HOK 3a & b 號,香港,CN,NaN,US,25375216,NaN,NaN,...,NaN,NaN,"Wednesday : 6:30 AM to 10:00 PM, Thursday : 6:...",22.284450,114.158460,NaN,NaN,NaN,NaN,NaN
4,太古廣場,https://www.starbucks.com/store-locator/store/17,"金鐘道太古廣場L1, 131號",香港,CN,0,US,29184762,NaN,NaN,...,NaN,NaN,"Wednesday : 7:00 AM to 9:30 PM, Thursday : 7:0...",22.277657,114.164619,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13613,Village Swindon,https://www.starbucks.com/store-locator/store/...,"Whitehill Way, Shaw Ridge Leisure Park",Swindon,GB,SN5 7DW,US,NaN,NaN,NaN,...,NaN,NaN,"Wednesday : 7:00 AM to 8:00 PM, Thursday : 7:0...",51.559830,-1.832880,NaN,NaN,NaN,NaN,NaN
13614,Xuchang Nanyang,https://www.starbucks.com/store-locator/store/...,"No.1, Nanyang St., Zhongzheng Dist., 2F",Taipei City,TW,10047,US,NaN,NaN,NaN,...,NaN,NaN,NaN,25.047001,121.509717,NaN,NaN,NaN,NaN,NaN
13615,Gothenburg Central Station,https://www.starbucks.com/store-locator/store/...,Drottningtorget 1,Gothenburg,SE,411 03,US,NaN,NaN,NaN,...,NaN,NaN,"Wednesday : 6:30 AM to 9:00 PM, Thursday : 6:3...",57.708750,11.973194,NaN,NaN,NaN,NaN,NaN
13616,Southside Marketplace.,https://www.starbucks.com/store-locator/store/...,"919 E. Fort Ave, Suite A",Baltimore,US,212305117,US,410 244-1934,NaN,NaN,...,NaN,NaN,"Wednesday : 5:00 AM to 10:00 PM, Thursday : 5:...",39.271266,-76.601215,NaN,NaN,NaN,NaN,NaN
13617,Wurzbach & NW Military,https://www.starbucks.com/store-locator/store/...,12003 NW Military Highway,San Antonio,US,78231,US,210-408-8398,NaN,NaN,...,NaN,NaN,"Wednesday : 5:00 AM to 10:00 PM, Thursday : 5:...",29.555890,-98.535469,NaN,NaN,NaN,NaN,NaN

In [21]:
map=folium.Map(location=[25.606390797877904, 85.15175855939738],zoom_start=3)
map.add_child(folium.Marker(location=[25.606390797877904,85.15175855939738],popup='This is my location',icon=folium.Icon(color='green')))
map.save('map1.html')

In [38]:
for i in range(df1['latitude'].size):
    map.add_child(folium.Marker(location=[df1['latitude'][i],df1['longitude'][i]],popup='Starbucks',icon=folium.Icon(color='green')))
map.save('map2.html')

In [78]:
from subprocess import run
from datetime import datetime
from threading import Timer

x=datetime.today()
# y=x.replace(day=x.day,hour=1,minute=4,second=0,microsecond=0)
# diff=y-x
# sec=x.second+1

def online():
    code=input('Enter the classroom code')
#     automata(code)

# def automata(code):
#     run('https://www.youtube.com/'+code)
      

Timer(2,online).start()

Enter the classroom code

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "<ipython-input-78-123f72418a2c>", line 11, in online
EOFError: EOF when reading a line

In [81]:
from threading import Timer
def hola():
    a=input('Enter the number')
    print(a)
    
Timer(1,hola).start()
Ti
print('This is before output')

This is before output
Enter the number

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "<ipython-input-81-7ef32fbb54a7>", line 3, in hola
EOFError: EOF when reading a line

In [18]:
ls=['hello','mellow']
ls

['hello', 'mellow']

In [21]:
import pandas as pd
import folium
import random
df

,VOLCANX020,NUMBER,NAME,LOCATION,STATUS,ELEV,TYPE,TIMEFRAME,LAT,LON
0,509.0,1201-01=,Baker,US-Washington,Historical,3285.0,Stratovolcanoes,D3,48.776798,-121.810997
1,511.0,1201-02-,Glacier Peak,US-Washington,Tephrochronology,3213.0,Stratovolcano,D4,48.111801,-121.111000
2,513.0,1201-03-,Rainier,US-Washington,Dendrochronology,4392.0,Stratovolcano,D3,46.869801,-121.751000
3,515.0,1201-05-,St. Helens,US-Washington,Historical,2549.0,Stratovolcano,D1,46.199799,-122.181000
4,516.0,1201-04-,Adams,US-Washington,Tephrochronology,3742.0,Stratovolcano,D6,46.205799,-121.490997
...,...,...,...,...,...,...,...,...,...,...
57,580.0,1210-03-,Valles Caldera,US-New Mexico,Pleistocene-Fumarolic,3430.0,Caldera,Q,35.869999,-106.570999
58,581.0,1209-02-,Sunset Crater,US-Arizona,Dendrochronology,2447.0,Cinder cone,D6,35.369999,-111.501000
59,584.0,1203-20-,Amboy,US-California,Holocene,288.0,Cinder cone,U,34.549999,-115.780998
60,586.0,1210-02-,Zuni-Bandera,US-New Mexico,Anthropology,2550.0,Volcanic field,D7,34.799999,-108.001000
61,588.0,1210-01-,Carrizozo,US-New Mexico,Holocene,1731.0,Cinder cone,U,33.780102,-105.931000

In [39]:
df=pd.read_csv('Volcanoes.csv')
vmap=folium.Map(location=[46.869801, -121.751000],zoom_start=5)
lat=list(df['LAT'])
lon=list(df['LON'])
name=list(df['NAME'])
height=list(df['ELEV'])
status=list(df['STATUS'])

html = """<h4>Volcano information:</h4>
Name: %s <br>
Height: %s <br>
Status: %s 
"""

colorList=['red', 'blue', 'green', 'purple', 'orange', 'darkred', 'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue', 'darkpurple','pink', 'lightblue', 'lightgreen', 'gray', 'black', 'lightgray']
def randomColorPicker():
    return random.choice(colorList)

for la,ln,nm,ht,st in zip(lat,lon,name,height,status):
    iframe = folium.IFrame(html=html %  , width=200, height=100)
    vmap.add_child(folium.Marker(location=[la,ln],popup=folium.Popup(iframe),icon=folium.Icon(color=randomColorPicker())))
vmap.save('VolcanoMap.html')

TypeError: not enough arguments for format string